#!/bin/bash

function dump_runtime() {
    echo env:
    env
    echo
    echo "args; $@"
    echo
    echo "pwd:"
    /bin/pwd
    echo
    echo "ls -alR:"
    ls -alR
    echo
    echo "hostname: `hostname`"
    echo
    echo filesystems:
    mount
    echo
    echo "ls -l /dev/hugepages"
    /bin/ls -l /dev/hugepages
    echo
    echo "/proc/meminfo"
    cat /proc/meminfo
    echo
    echo DPDK devices:
    dpdk-devbind -s
    echo
    echo netdevs:
    ls -l /sys/class/net
    echo
    echo ip a:
    ip a
    echo
    echo "per-node-hugepages:"
    for n in 0 1; do
        path="/sys/devices/system/node/node$n/hugepages/hugepages-1048576kB"
        echo $path
        for i in `/bin/ls -1 $path`; do
            echo $i:
            cat $path/$i
        done
    done
}

function validate_label() {
    id=`echo $RS_CS_LABEL | awk -F- '{print $2}'`
    re='^[1-9][0-9]*$'
    if [[ ! "$id" =~ $re ]]; then
        echo "ID must a be a positive interger, exiting"
        exit 1
    fi
}


function validate_sw_prereqs() {
    local missing=""
    local bail=0
    for bin in getopt ip ss jq ss uperf; do
        $bin -h 2>&1 >/dev/null || (bail=1 && missing+=" $bin")
    done
    if [ "$bail" == "1" ]; then
        echo "ERROR: could not find utility: $missing"
        exit 1
    fi
}
